const Icons = {
  location: require('../assets/icons/location.png'),
  citation: require('../assets/icons/citation.png'),
  citation_fill: require('../assets/icons/citation_fill.png'),
  tour: require('../assets/icons/tour.png'),
  tour_fill: require('../assets/icons/tour_fill.png'),
  like: require('../assets/icons/like.png'),
  like_fill: require('../assets/icons/like_fill.png'),
  left_arrow: require('../assets/icons/left_arrow.png'),
  landMark: require('../assets/icons/landMark.png'),
  complete: require('../assets/icons/complete.png'),
  prev: require('../assets/icons/prev.png'),
  next: require('../assets/icons/next.png'),
  pause: require('../assets/icons/pause.png'),
  play: require('../assets/icons/play.png'),
  marker: require('../assets/icons/marker.png'),
  sliderThumb: require('../assets/icons/sliderThumb.png'),
  tick: require('../assets/icons/tick.png'),
  blank_circle: require('../assets/icons/blank_circle.png'),
  menu: require('../assets/icons/menu.png'),
  appIcon: require('../assets/icons/appIcon.png'),
};
export default Icons;
